# This is a basic workflow to help you get started with Actions

name: test-ssh

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the stage branch
  push:
    branches: 
      - stage 
        master
  
  
jobs:
  name: Build
    runs-on: ubuntu-latest
    steps:
    - name: execute ssh command via using private key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USER }}
        key: ${{ secrets.SSH_KEY }}
        run: pwd
