# This is a basic workflow to help you get started with Actions

name: test-ssh
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the stage 
  push:
    branches: 
      - stage 
        master
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.STAGING_HOST }}
         username: ${{ secrets.STAGING_USER }}
         key: ${{ secrets.SSH_KEY }}
     - run: |
         pwd
